apiVersion: apps/v1
kind: Deployment
metadata:
  name: token
  #namespace: "challengespace"
  namespace: "ingress-nginx"
  labels:
    app: token
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
      - name: token
        image: idboubacar/challenge-semestre2-token-api
        imagePullPolicy: Always
        envFrom:
          - secretRef:
            name: production-secret
        ports:
          - containerPort: 80