trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'your-azure-subscription'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: 'scripts/deploy.sh'