apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  namespace: "challengespace"
  labels:
    app: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: idboubacar/challenge-semestre2-training-api
        imagePullPolicy: Always
      envFrom:
        - secretRef:
          name: production-secret
      ports:
        - containerPort: 80