apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: "challengespace"
  labels:
    name: training
    app: training
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 80
  selector:
    app: training