gateway-api:
  image:
    repository: challengesemestre2.azurecr.io/gateway-api
    tag: latest
  service:
    port: 8000
    targetPort: 8000

  ingress:
    enabled: true
    hostname: gateway-api.example.com

    # env:
    #   - name: SPRING_PROFILES_ACTIVE
    #     value: "default"
    #   - name: SPRING_DATASOURCE_URL
    #     value: "jdbc:postgresql://postgres:5432/challenge-semestre2"
    #   - name: SPRING_DATASOURCE_USERNAME
    #     value: "postgres"
    #   - name: SPRING_DATASOURCE_PASSWORD
    #     value: "postgres"
    #   - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    #     value: "org.postgresql.Driver"
    #   - name: SPRING_JPA_HIBERNATE_DDL_AUTO
    #     value: "update"
    #   - name: SPRING_JPA_SHOW_SQL
    #     value: "true"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
    #     value: "true"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS
    #     value: "true"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
    #     value: "org.hibernate.dialect.PostgreSQLDialect"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_NAMING_STRATEGY
    #     value: "org.hibernate.cfg.ImprovedNamingStrategy"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE
    #     value: "50"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_INSERTS
    #     value: "true"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES
    #     value: "true"
    #   - name: SPRING_JPA_PROPERTIES_HIBERNATE_BATCH_VERSIONED_DATA
    #     value: "true"
    #   - name: SPR