apiVersion: apps/v1

kind: Deployment

metadata:
  name: gateway

  labels:
    app: gateway

spec:
  replicas: 3

  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway
  spec:
    containers:
    - name: gateway

      image: idboubacar/challenge-semestre2-gateway-api:latest
      env:
        - name: PORT
          value: "80"
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 80