---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gateway-api"
  namespace: "default"
  labels:
    app: "gateway-api"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "gateway-api"
  template:
    metadata:
      labels:
        app: "gateway-api"
    spec:
      containers:
        - name: "gateway-api"
          image: "idboubacar/challenge-semestre2-gateway-api:latest"
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

# ---
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: gateway
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: gateway
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         targetAverageUtilization: 50

        

