---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gateway-api-service"
  namespace: "challengespace"
  labels:
    app: "gateway-api"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  selector:
    app: "gateway-api"
  type: "LoadBalancer"