apiVersion: "v1"
kind: "Service"
metadata:
  name: challenge-gateway
  namespace: "default"
  labels:
    app: challenge-gateway
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: challenge-gateway