# apiVersion: v1
# kind: Service
# metadata:
#     name: "gateway-api"
#     labels:
#         app: "gateway-api"
# spec:
#     type: LoadBalancer
#     ports:
#     - port: 8000
#       targetPort: 8000
#       protocol: TCP
#       name: http
#     selector:
#         app: "gateway-api"
#service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway-api
spec:
  type: ClusterIP
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http