apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: "challengespace"
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        #image: mychallengeregistry.azurecr.io/challenge-user:latest
        image: idboubacar/challenge-semestre2-user-api
        ressource:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 128Mi
          
        env:
          - name: USER_SERVICE_PORT
            value: "80"
          - name: MONGO_DSN
            value: mongodb://44.212.32.217:27017/user_db
          - name: API_GATEWAY_PORT
            value: "8000"
          - name: MAILER_SERVICE_PORT
            value: "8008"
          - name: MAILER_SERVICE_HOST
            value: mailer-api
        ports:
          - containerPort: 80