apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: "challengespace"
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: idboubacar/challenge-semestre2-user-api
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: production-secret-user
        ports:
        - containerPort: 80  