apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: "challengespace"
  labels:
    name: user
    app: user
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 80
  selector:
    app: user