apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition
  namespace: "challengespace"
  labels:
    app: nutrition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrition
  template:
    metadata:
      labels:
        app: nutrition
    spec:
      containers:
      - name: nutrition
        image: idboubacar/challenge-semestre2-nutrition-api
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: production-secret-nutrition
        ports:
        - containerPort: 80