apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
  #namespace: "challengespace"
  namespace: "ingress-nginx"
  labels:
    app: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
      - name: messenger
        image: idboubacar/challenge-semestre2-messenger-api
        imagePullPolicy: Always
      envFrom:
        - secretRef:
          name: production-secret
      ports:
        - containerPort: 80