apiVersion: v1
kind: Service
metadata:
  name: messenger
  #namespace: "challengespace"
  namespace: "ingress-nginx"
  labels:
    name: messenger
    app: messenger
spec:
  type: ClusterIP
  ports:
    - port: 8010
      targetPort: 80
  selector:
    app: messenger