apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  #namespace: "challengespace"
  namespace: "ingress-nginx"
  labels:
    app: subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
      - name: subscription
        image: idboubacar/challenge-semestre2-subscription-api:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
            name: production-secret
        ports:
          - containerPort: 80
