apiVersion: v1
kind: Service
metadata:
  name: subscription
  namespace: "challengespace"
  labels:
    name: subscription
    app: subscription
spec:
  type: ClusterIP
  ports:
    - port: 8009
      targetPort: 80
  selector:
    app: subscription