apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  #namespace: "challengespace"
  namespace: "ingress-nginx"
  labels:
    app: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer
        image: mychallengeregistry.azurecr.io/challenge-mailer:latest
        imagePullPolicy: Always
        #image: idboubacar/challenge-semestre2-mailer-api
        # ressource:
        # limits:
        #   cpu: 500m
        #   memory: 128Mi
        # requests:
        #   cpu: 250m
        #   memory: 128Mi

        env:
          - name: MAILER_SERVICE_PORT
            value: "80"
          - name: MAILER_DISABLED
            value: "0"
          - name: MAILER_FROM
            value: "fitnesslovers163@gmail.com"
          - name: MAIL_USERNAME
            value: "FitnessLovers"
          - name: MAIL_PASSWORD
            value: "FitnessLovers163"
          - name: OAUTH_CLIENTID
            value: "1060019283748-maltel1pmdhpijps3972pbcnr1t6oipq.apps.googleusercontent.com"
          - name: OAUTH_CLIENT_SECRET
            value: "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"
          - name: OAUTH_REFRESH_TOKEN
            value: "1//049znWotTda2OCgYIARAAGAQSNwF-L9IrZbheUcZK6sDcvcjK-XSAhie677iRgFLVQ8ew1jYOWzjb-7UyY-lOQFJ4PzT8phmKwP0"
        ports:
          - containerPort: 80