apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  #namespace: "challengespace"
  namespace: "ingress-nginx"
  labels:
    app: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
      - name: mailer
        image: idboubacar/challenge-semestre2-mailer-api
        imagePullPolicy: Always
      envFrom:
        - secretRef:
          name: production-secret
      ports:
        - containerPort: 80