apiVersion: v1
kind: Service
metadata:
  name: mailer
  namespace: "challengespace"
  labels:
    name: mailer
    app: mailer
spec:
  type: ClusterIP
  ports:
    - port: 8008
      targetPort: 80
  selector:
    app: mailer