version: '3.9'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  # postgres
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./initdb/init-postgres-db.sql:/docker-entrypoint-initdb.d/init-postgres-db.sql:ro

  # mongo-db
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
