version: '3.9'

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  # postgres
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  # mongo-db
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      #MONGO_INITDB_ROOT_USERNAME: mongo_user
      #MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - ./mongodata:/data/db