version: '3.9'

services:
  front:
    build:
      context: ../front
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: front
    env_file:
      - ../front/.env
    volumes:
      - ../front:/var/www/front
    ports:
      - 3000:3000

  gateway-api:
    build:
      context: ../gateway-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: gateway-api
    env_file:
      - ../gateway-api/.env
    volumes:
      - ./:/gateway-api
    ports:
      - 8000:8000

  nutrition-api:
    build:
      context: ../nutrition-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: nutrition-api
    env_file:
      - ../nutrition-api/.env
    volumes:
      - ../nutrition-api:/var/www/nutrition-api
    ports:
      - 8001:8001

  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: user-api
    env_file:
      - ../user-api/.env
    volumes:
      - ../user-api:/var/www/user-api
    ports:
      - 8002:8002

  training-api:
    build:
      context: ../training-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: training-api
    env_file:
      - ../training-api/.env
    volumes:
      - ../training-api:/var/www/training-api
    ports:
      - 8003:8003

  analytic-api:
    build:
      context: ../analytic-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: analytic-api
    env_file:
      - ../analytic-api/.env
    volumes:
      - ../analytic-api:/var/www/analytic-api
    ports:
      - 8005:8005

  token-api:
    build:
      context: ../token-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: token-api
    env_file:
      - ../token-api/.env
    volumes:
        - ../token-api:/var/www/token-api
    ports:
      - 8006:8006

  permission-api:
    build:
      context: ../permission-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: permission-api
    env_file:
      - ../permission-api/.env
    volumes:
        - ../permission-api:/var/www/permission-api
    ports:
      - 8007:8007

  mailer-api:
    build:
      context: ../mailer-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: mailer-api
    env_file:
      - ../mailer-api/.env
    volumes:
        - ../mailer-api:/var/www/mailer-api
    ports:
      - 8008:8008

  subscription-api:
    build:
      context: ../subscription-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: subscription-api
    env_file:
      - ../subscription-api/.env
    volumes:
        - ../subscription-api:/var/www/subscription-api
    ports:
      - 8009:8009
  messenger-api:
    build:
      context: ../messenger-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: messenger-api
    env_file:
      - ../messenger-api/.env
    volumes:
        - ../messenger-api:/var/www/messenger-api
    ports:
      - 9000:9000