version: '3.9'

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure

services:
  gateway-api:
    build:
      context: ../gateway-api
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      dockerfile: ../gateway-api/Dockerfile
    hostname: gateway-api
    env_file:
      - ../gateway-api/.env
    volumes:
      - ../gateway-api:/usr/src/gateway-api
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend

  analytic-api:
    build:
      context: ../analytic-api
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      dockerfile: ../gateway-api/Dockerfile
    hostname: analytic-api
    env_file:
      - ../analytic-api/.env
    volumes:
      - ../analytic-api:/usr/src/analytic-api
    ports:
      - "3001:3001"
    networks:
      - backend

  nutrition-api:
    build:
      context: ../nutrition-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: nutrition-api
    env_file:
      - ../nutrition-api/.env
    volumes:
      - ../nutrition-api:/var/www/nutrition-api
      - /var/www/nutrition-api/node_modules
    ports:
      - 8001:8001

  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: user-api
    env_file:
      - ../user-api/.env
    volumes:
      - ../user-api:/var/www/user-api
      - /var/www/user-api/node_modules
    ports:
      - 8002:8002

  training-api:
    build:
      context: ../training-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: training-api
    env_file:
      - ../training-api/.env
    volumes:
      - ../training-api:/var/www/training-api
      - /var/www/training-api/node_modules
    ports:
      - 8003:8003

  token-api:
    build:
      context: ../token-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: token-api
    env_file:
      - ../token-api/.env
    volumes:
        - ../token-api:/var/www/token-api
        - /var/www/token-api/node_modules
    ports:
      - 8006:8006

  permission-api:
    build:
      context: ../permission-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: permission-api
    env_file:
      - ../permission-api/.env
    volumes:
        - ../permission-api:/var/www/permission-api
        - /var/www/permission-api/node_modules
    ports:
      - 8007:8007

  mailer-api:
    build:
      context: ../mailer-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: mailer-api
    env_file:
      - ../mailer-api/.env
    volumes:
        - ../mailer-api:/var/www/mailer-api
        - /var/www/mailer-api/node_modules
    ports:
      - 8008:8008

  subscription-api:
    build:
      context: ../subscription-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: subscription-api
    env_file:
      - ../subscription-api/.env
    volumes:
        - ../subscription-api:/var/www/subscription-api
        - /var/www/subscription-api/node_modules
    ports:
      - 8009:8009
  messenger-api:
    build:
      context: ../messenger-api
      dockerfile: Dockerfile
      target: development-build-stage
    hostname: messenger-api
    env_file:
      - ../messenger-api/.env
    volumes:
        - ../messenger-api:/var/www/messenger-api
        - /var/www/messenger-api/node_modules
    ports:
      - 9000:9000