version: '3.9'

services:
<<<<<<< HEAD
=======

>>>>>>> feature/fix-docker
  gateway-api:
    build:
      context: ../gateway-api
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      dockerfile: Dockerfile      
      target: production-build-stage
    hostname: gateway-api
    env_file:
      - ../gateway-api/.env
    volumes:
      - ../gateway-api:/usr/src/gateway-api
      - /usr/src/gateway-api/node_modules
    ports:
      - "8000:8000"

  analytic-api:
    build:
      context: ../analytic-api
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      dockerfile: Dockerfile
      target: development
    hostname: analytic-api
    env_file:
      - ../analytic-api/.env
    volumes:
      - ../analytic-api:/usr/src/analytic-api
    ports:
      - "8005:8005"

  nutrition-api:
    build:
      context: ../nutrition-api      
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      dockerfile: Dockerfile
      target: development
    hostname: nutrition-api
    env_file:
      - ../nutrition-api/.env
    volumes:
      - ../nutrition-api:/usr/src/nutrition-api
    ports:
      - 8001:8001

  user-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../user-api
      dockerfile: Dockerfile
      target: development
    hostname: user-api
    env_file:
      - ../user-api/.env
    volumes:
      - ../user-api:/usr/src/user-api
    ports:
      - 8002:8002

  training-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../training-api
      dockerfile: Dockerfile
      target: development
    hostname: training-api
    env_file:
      - ../training-api/.env
    volumes:
      - ../training-api:/usr/src/training-api
    ports:
      - 8003:8003

  token-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../token-api
      dockerfile: Dockerfile
      target: development
    hostname: token-api
    env_file:
      - ../token-api/.env
    volumes:
        - ../token-api:/usr/src/token-api
    ports:
      - 8006:8006

  permission-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../permission-api
      dockerfile: Dockerfile
      target: development
    hostname: permission-api
    env_file:
      - ../permission-api/.env
    volumes:
        - ../permission-api:/usr/src/permission-api
    ports:
      - 8007:8007

  mailer-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../mailer-api
      dockerfile: Dockerfile
      target: development
    hostname: mailer-api
    env_file:
      - ../mailer-api/.env
    volumes:
        - ../mailer-api:/usr/src/mailer-api
    ports:
      - 8008:8008

  subscription-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../subscription-api
      dockerfile: Dockerfile
      target: development
    hostname: subscription-api
    env_file:
      - ../subscription-api/.env
    volumes:
        - ../subscription-api:/usr/src/subscription-api
    ports:
      - 8009:8009

  messenger-api:
    build:
      platforms:
        - "linux/amd64"
        - "linux/x86_64"
      context: ../messenger-api
      dockerfile: Dockerfile
      target: development
    hostname: messenger-api
    env_file:
      - ../messenger-api/.env
    volumes:
        - ../messenger-api:/usr/src/messenger-api
    ports:
      - 9000:9000