apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-users-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-users
spec:
  selector:
    app: mongodb-users
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-users
  namespace: "challengespace"
spec:
  selector:
    matchLabels:
      app: mongodb-users
  template:
    metadata:
      labels:
        app: mongodb-users
    spec:
      containers:
        - name: mongodb-users
          image: mongo:6.0.2-focal
          imagePullPolicy: "Always"
          env: 
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "mongouser"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "mongopassword"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongodb-users-pvc