apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-analytic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-analytic
spec:
  selector:
    app: mongodb-analytic
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-analytic
  namespace: "challengespace"
spec:
  selector:
    matchLabels:
      app: mongodb-analytic
  template:
    metadata:
      labels:
        app: mongodb-analytic
    spec:
      containers:
        - name: mongodb-analytic
          image: mongo:6.0.2-focal
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongodb-analytic-pvc