apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic
  namespace: "challengespace"
  labels:
    app: analytic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytic
  template:
    metadata:
      labels:
        app: analytic
    spec:
      containers:
      - name: analytic
        image: idboubacar/challenge-semestre2-analytic-api
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: production-secret
        ports:
        - containerPort: 80