apiVersion: v1
kind: Service
metadata:
  name: analytic
  namespace: "challengespace"
  labels:
    name: analytic
    app: analytic
spec:
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: 80
  selector:
    app: analytic