apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: idboubacar/challenge-semestre2-gateway-api
          ports:
            - containerPort: 3000

