apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: "challengespace"
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: idboubacar/challenge-semestre2-gateway-api:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
            name: production-secret
        ports:
          - containerPort: 8000