apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: "challengespace"
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: challengeiw3.azurecr.io/challenge-gateway:latest
        imagePullPolicy: Always
        env:
          - name: API_GATEWAY_PORT
            value: "8000"
        ports:
          - containerPort: 8000