apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission
  namespace: "challengespace"
  labels:
    app: permission
spec:
  replicas: 3
  selector:
    matchLabels:
      app: permission
  template:
    metadata:
      labels:
        app: permission
    spec:
      containers:
      - name: permission
        #image: mychallengeregistry.azurecr.io/challenge-permission:latest
        image: idboubacar/challenge-semestre2-permission-api
        env:
          - name: PERMISSION_SERVICE_PORT
            value: "80"
        ports:
          - containerPort: 80