apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission
  namespace: "challengespace"
  labels:
    app: permission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission
  template:
    metadata:
      labels:
        app: permission
    spec:
      containers:
      - name: permission
        image: idboubacar/challenge-semestre2-permission-api
        imagePullPolicy: Always
      envFrom:
        - secretRef:
          name: production-secret
      ports:
        - containerPort: 80