name: Azure -- docker image --> aks
on:
  push:
    branches: ["feature/aksBoubacar"]
    paths:
      - ".github/workflows/azure-aks-deploy.yml"
      - "manifests/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: challengeiw3.azurecr.io
          username: challengeiw3
          password: NQKUHlqpCO3r8l/jt0vlrsPmUnHDhNIAR9Q7MqcR6/+ACRDBVPUJ

      - run: |
          az login          
          az account set --subscription 3e16dd7c-61e5-4d26-946a-5e09d779e669
          az aks get-credentials --resource-group challenge_iw3 --name myAKSCluster
  
      - name: Deploy to AKS
        env: 
          AZURECRNAME: challengeiw3
          AZURECRUSERNAME: challengeiw3
          AZURECRPASSWORD: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          az aks get-credentials --resource-group challenge_iw3 --name myAKSCluster
          kubectl apply -f ./manifests/gateway/
          kubectl apply -f ./manifests/user/
          kubectl apply -f ./manifests/analytic/
          kubectl apply -f ./manifests/mailer/
          kubectl apply -f ./manifests/messenger/
          kubectl apply -f ./manifests/nutrition/
          kubectl apply -f ./manifests/permission/
          kubectl apply -f ./manifests/subscription/
          kubectl apply -f ./manifests/token/
          kubectl apply -f ./manifests/training/
          kubectl get pods -n challengespace
          kubectl get service -n challengespace
          kubectl get deployments -n challengespace
          kubectl rollout restart deployment gateway -n challengespace
          kubectl rollout restart deployment analytic -n challengespace
          kubectl rollout restart deployment mailer -n challengespace
          kubectl rollout restart deployment messenger -n challengespace
          kubectl rollout restart deployment nutrition -n challengespace
          kubectl rollout restart deployment user -n challengespace
          kubectl rollout restart deployment permission -n challengespace
          kubectl rollout restart deployment subscription -n challengespace
          kubectl rollout restart deployment token -n challengespace
          kubectl rollout restart deployment training -n challengespace