name: Azure K8S deploy

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  push:
    branches: ["fetaure/yatera"]
    paths:
      - ".github/workflows/azure-aks-deploy.yml"
      - "manifests/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            cluster-name: challengeSemestreAKS
            resource-group: FR_CHALLENGE_SEMESTRE2

      - name: Create namespace
        run: |
          namespacePresent=`kubectl get namespace | grep challengeSpace | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace challengeSpace`
          fi

      - uses: azure/k8s-deploy@v1.2
        with:
          namespace: challengeSpace
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            mohammaddocker/joke-api:latest