name: Azure K8S deploy new
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  push:
    branches: ["feature/yatera"]
    paths:
      - ".github/workflows/azure-aks-deploy.yml"
      - "manifests/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: 91535987-15e2-4b95-8939-8c811e6dda18
          tenant-id: c371d4f5-b34f-4b06-9e66-517fed904220
          subscription-id: e354bc29-fa51-443a-be90-a1191487a664
      - run: |
          az acr login -n myvoteacr
          az account set --subscription e354bc29-fa51-443a-be90-a1191487a664
          az aks get-credentials --resource-group myVoteGroup --name myAKSCluster
          docker tag idboubacar/challenge-semestre2-gateway-api:latest myvoteacr.azurecr.io/challenge-gateway:latest
          docker push myvoteacr.azurecr.io/challenge-gateway:latest
          az acr repository list --name myvoteacr --output table


      # - uses: Azure/aks-set-context@v1
      #   with:
      #       creds: '${{ secrets.AZURE_CREDENTIALS }}'
      #       cluster-name: myAKSCluster
      #       resource-group: myVoteGroup

      # - uses: azure/k8s-deploy@v1.2
      #   with:
      #     namespace: "default"
      #     manifests: |
      #       manifests/deployment-azure.yaml
      #     images: |
      #       idboubacar/challenge-semestre2-gateway-api:latest