name: gateway deployment
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  push:
    branches: ["gateway_deploy"]
    paths:
      - ".github/workflows/gateway-deploy.yml"
      - "gateway-api/**"
      - "manifests/gateway"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az acr login -n challengeiw3 --expose-token
          az account set --subscription 3e16dd7c-61e5-4d26-946a-5e09d779e669
          az aks get-credentials --resource-group challenge_iw3 --name myAKSCluster

      - name: Build and push
        run: |
          docker build "./gateway-api" -f  "./gateway-api/Dockerfile" -t challengeiw3.azurecr.io/challenge-gateway:latest

          docker push challengeiw3.azurecr.io/challenge-gateway:latest

          az acr repository list --name challengeiw3 --output table
          az acr repository show-tags --name challengeiw3 --repository challenge-gateway --output table

      #- name: Deploy to AKS
        # env:
        #   AZURECRNAME: challengeiw3
        #   AZURECRUSERNAME: challengeiw3
        #   AZURECRPASSWORD: ${{ secrets.AZURE_CREDENTIALS }}
        # run: |
        #   az aks get-credentials --resource-group challenge_iw3 --name myAKSCluster
        #   kubectl delete namespaces challengespace
        #   kubectl create namespace challengespace
        #   kubectl apply -f ./manifests/gateway/
        # kubectl rollout restart deployment gateway -n ingress-nginx









      # - uses: Azure/aks-set-context@v1
      #   with:
      #       creds: '${{ secrets.AZURE_CREDENTIALS }}'
      #       cluster-name: myAKSCluster
      #       resource-group: myVoteGroup

      # - uses: azure/k8s-deploy@v1.2
      #   with:
      #     namespace: "default"
      #     manifests: |
      #       manifests/deployment-azure.yaml
      #     images: |
      #       idboubacar/challenge-semestre2-gateway-api:latest