name: Continuous Integration 

on:
  push:
    branches: feature/yatera

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push analytics
        id: docker_build_analytics_service
        uses: docker/build-push-action@v2
        with:
          context: ./analytic-api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/challenges2-bo-analytic-api:ci
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
