name: user deployment
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
  push:
    branches: ["feature/testdocker"]
    paths:
      - ".github/workflows/user-deploy.yml"
      - "user-api/**"
      - "manifests/user"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: challengeiw3.azurecr.io
          username: challengeiw3
          password: NQKUHlqpCO3r8l/jt0vlrsPmUnHDhNIAR9Q7MqcR6/+ACRDBVPUJ
          
      - run: |
          az login
          az acr login -n challengeiw3
          az account set --subscription 3e16dd7c-61e5-4d26-946a-5e09d779e669
          az aks get-credentials --resource-group challenge_iw3 --name myAKSCluster
      
      - name: Build and push
        run: |
          docker build "./user-api" -f  "./user-api/Dockerfile" -t challengeiw3.azurecr.io/challenge-user:latest

          docker push challengeiw3.azurecr.io/challenge-user:latest

          az acr repository list --name challengeiw3 --output table
          az acr repository show-tags --name challengeiw3 --repository challenge-user --output table

      - name: Deploy to AKS
        env: 
          AZURECRNAME: challengeiw3
          AZURECRUSERNAME: challengeiw3
          AZURECRPASSWORD: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          az aks get-credentials --resource-group challenge_iw3 --name myAKSCluster
          kubectl get namespace | grep -q "^challengespace " || kubectl create namespace challengespace
          kubectl apply -f ./manifests/user/
          kubectl get pods -n challengespace
          kubectl get service -n challengespace
          kubectl get deployments -n challengespace        
      # kubectl rollout restart deployment user -n challengespace










      # - uses: Azure/aks-set-context@v1
      #   with:
      #       creds: '${{ secrets.AZURE_CREDENTIALS }}'
      #       cluster-name: myAKSCluster
      #       resource-group: myVoteGroup

      # - uses: azure/k8s-deploy@v1.2
      #   with:
      #     namespace: "default"
      #     manifests: |
      #       manifests/deployment-azure.yaml
      #     images: |
      #       idboubacar/challenge-semestre2-user-api:latest